# -*- coding: utf-8 -*-
"""Untitled2.ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DrHs6C8zcbtVQNkQpmieSZ1cx5Z55dkg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer,SimpleImputer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss

from collections import Counter

df = pd.read_csv('/content/Uterine Corpus Endometrial Carcinoma.csv')

df.head()

df.shape

df.info()

df.describe()

final_df = df.drop(['Patient ID', 'Sample ID', 'Cancer Type Detailed', 'Race Category'], axis=1)

final_df.rename(columns={'Tumor Type' :'Tumor Hystopathological classification', 'Subtype' : 'Tumor Molecular classification'}, inplace=True)

final_df = final_df[['Tumor Hystopathological classification', 'Tumor Molecular classification', 'Diagnosis Age', 'MSI MANTIS Score', 'MSIsensor Score', 'Mutation Count', 'Fraction Genome Altered', 'Overall Survival Status', 'Disease Free Status', 'Disease-specific Survival status']]

final_df

num_features = final_df.select_dtypes(exclude='object').columns

sns.set(style="whitegrid")

fig,axs = plt.subplots(3,2, figsize = (8, 10))

sns.histplot(data=final_df, x=num_features[0], kde=True, color="skyblue", ax=axs[0, 0])

sns.histplot(data=final_df, x=num_features[1], kde=True, color="olive", ax=axs[0, 1])

sns.histplot(data=final_df, x=num_features[2], kde=True, color="gold", ax=axs[1, 0])

sns.histplot(data=final_df, x=num_features[3], kde=True, color="teal", ax=axs[1, 1])

sns.histplot(data=final_df, x=num_features[4], kde=True, color="bisque", ax=axs[2, 0])

fig.tight_layout()

plt.show()

final_df.isna().sum()

msno.matrix(final_df)
plt.show()

mean_imputer = SimpleImputer(strategy='mean')

final_df['Diagnosis Age'] = mean_imputer.fit_transform(final_df[['Diagnosis Age']])

median_imputer = SimpleImputer(strategy='median')

final_df[['MSI MANTIS Score', 'MSIsensor Score', 'Mutation Count', 'Fraction Genome Altered']] = median_imputer.fit_transform(final_df[['MSI MANTIS Score', 'MSIsensor Score', 'Mutation Count', 'Fraction Genome Altered']])

final_df.isna().sum()

msno.matrix(final_df)
plt.show()

le_df1 = final_df.copy()

le1 = LabelEncoder()

le1.fit(le_df1['Tumor Molecular classification'])

le_df1['Tumor Molecular classification cat'] = le1.transform(le_df1['Tumor Molecular classification'])
le_df1['Tumor Molecular classification cat'] = le_df1['Tumor Molecular classification cat'].apply(lambda x: np.nan if x == 4 else x)

imputer = IterativeImputer()

X = le_df1[['MSI MANTIS Score', 'MSIsensor Score', 'Mutation Count', 'Fraction Genome Altered', 'Tumor Molecular classification cat']]

X_imputed = imputer.fit_transform(X)
le_df1['Tumor Molecular classification cat']= X_imputed[:, 4].round()
mc_imputed = le1.inverse_transform(le_df1['Tumor Molecular classification cat'].astype('int'))

final_df['Tumor Molecular classification'] = mc_imputed

le_df2 = final_df.copy()
le2 = LabelEncoder()

le2.fit(le_df2['Tumor Molecular classification'])

le_df2['Tumor Molecular classification cat'] = le2.transform(le_df2['Tumor Molecular classification'])

le2.fit(le_df2['Disease Free Status'])

le_df2['Disease Free Status cat'] = le2.transform(le_df2['Disease Free Status'])

le_df2[['Tumor Molecular classification', 'Tumor Molecular classification cat', 'Disease Free Status', 'Disease Free Status cat']]

le_df2['Disease Free Status cat'] = le_df2['Disease Free Status cat'].apply(lambda x: np.nan if x == 2 else x)

imputer2 = IterativeImputer()
X_2 = le_df2[['Tumor Molecular classification cat', 'MSI MANTIS Score', 'MSIsensor Score', 'Mutation Count', 'Fraction Genome Altered', 'Disease Free Status cat']]

X_imputed_2 = imputer.fit_transform(X_2)

le_df2['Disease Free Status cat']= X_imputed_2[:, 5].round()

dsf_imputed = le2.inverse_transform(le_df2['Disease Free Status cat'].astype('int'))

final_df['Disease Free Status'] = dsf_imputed

print('Original df with Nan', ':', df['Disease Free Status'].value_counts(),
      'Final df with imputed values', ':', final_df['Disease Free Status'].value_counts())

final_df.isna().sum()

final_df.loc[final_df['Disease-specific Survival status'].isna(), 'Disease-specific Survival status'] = '0:ALIVE OR DEAD TUMOR FREE'

final_df.isna().sum()

msno.matrix(final_df)
plt.show()

final_df.duplicated().sum()

sns.countplot(x='Tumor Hystopathological classification', data=final_df, palette="Set1", edgecolor='black')

plt.xticks(rotation=45)

plt.show()

sns.countplot(x='Tumor Molecular classification', data=final_df, palette='Set1', edgecolor='black')

plt.xticks(rotation=45)

plt.show()

sns.heatmap(final_df.select_dtypes(exclude='object').corr(), annot=True, cmap='coolwarm')

plt.show()

sns.scatterplot(data=final_df, x='MSIsensor Score', y='MSI MANTIS Score', hue='Tumor Molecular classification')

sns.scatterplot(data=final_df, x='MSI MANTIS Score', y='Mutation Count', hue='Tumor Molecular classification')

sns.scatterplot(data=final_df, y='Fraction Genome Altered', x='MSI MANTIS Score', hue='Tumor Molecular classification')

sns.scatterplot(data=final_df, x='Mutation Count', y='Fraction Genome Altered', hue='Tumor Molecular classification')

X = final_df[['Mutation Count', 'Fraction Genome Altered', 'MSI MANTIS Score', 'MSIsensor Score']]

y = final_df['Tumor Molecular classification']

scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(X_scaled, columns=['Mutation Count', 'Fraction Genome Altered', 'MSI MANTIS Score', 'MSIsensor Score'])

X_scaled.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=100)

counter = Counter(y_train)
print('Before', ':', counter)

sm = SMOTE()
X_train_sm, y_train_sm = sm.fit_resample(X_train, y_train)

counter = Counter(y_train_sm)
print('After', ':', counter)

model = KNeighborsClassifier()

grid = {
    'n_neighbors': np.arange(2, 30)
        }

search = GridSearchCV(model, grid, scoring='accuracy', cv=5, n_jobs=-1)
search.fit(X_train_sm, y_train_sm)

search.best_params_

knn_model = KNeighborsClassifier(n_neighbors=4)

knn_model.fit(X_train_sm, y_train_sm)

y_pred = knn_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred) * 100

accuracy

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

X = final_df.drop("Tumor Molecular classification", axis=1)
y = final_df["Tumor Molecular classification"]

# Identify categorical and numerical columns in X
categorical_features = X.select_dtypes(include=['object']).columns
numerical_features = X.select_dtypes(exclude=['object']).columns

# Create a column transformer for one-hot encoding categorical features and scaling numerical features
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('num', MinMaxScaler(), numerical_features)
    ])

# Create a pipeline with preprocessing and logistic regression
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=2000))
])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit the pipeline
model_pipeline.fit(X_train, y_train)

import seaborn as sns
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

y_pred_lr = model_pipeline.predict(X_test)
cm = confusion_matrix(y_test, y_pred_lr)

sns.heatmap(cm, annot=True, fmt="d")
plt.xlabel("Tahmin")
plt.ylabel("Gerçek")
plt.show()

from sklearn.metrics import classification_report
import pandas as pd

report = classification_report(y_test, y_pred_lr, output_dict=True)
df_report = pd.DataFrame(report).transpose()

df_report[['precision','recall','f1-score']].plot(kind='bar')
plt.show()